# Generated by Django 4.1.1 on 2022-09-21 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spendings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('spent_at', models.DateField(default=datetime.date.today)),
                ('currency', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
