# Generated by Django 4.1.1 on 2022-09-21 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_spendings_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendings',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spendings',
            name='spent_at',
            field=models.DateField(default=datetime.date),
        ),
    ]
