# Generated by Django 4.1.1 on 2022-09-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_spendings_amount_alter_spendings_spent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendings',
            name='spent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
